name: adhan_dart
version: 2.0.1
description: >-
    Library to calculate prayer times for muslims.
    Based on precise astronomical formula.
repository: https://github.com/prayer-timetable/adhan_dart
issue_tracker: https://github.com/prayer-timetable/adhan_dart/issues
topics:
    - prayer-times
    - islamic
    - adhan
    - salah
environment:
    sdk: '>=2.19.0  <4.0.0'
dependencies:

dev_dependencies:
    test: ^1.31.1
    timezone: ^0.11.0
    lints: ^6.1.0
